# mock might needed in all places
# use original interface name as name, we use a dedicated `mocks` package to make the context clear
structname: "{{.InterfaceName}}"
# snake case file names
filename: "{{.InterfaceName | snakecase}}.go"
# place all mocks in the mocks package
pkgname: "mocks"
# all mocks should live near their interfaces
dir: "{{.InterfaceDirRelative}}/mocks"
template: testify

# mocks to generate
packages:
  "flamingo.me/httpcache":
    interfaces:
      Backend:
      TagSupporting: