inpackage: false
testonly: false
keeptree: true
with-expecter: true
mockname: "{{.InterfaceName}}"
filename: "{{.InterfaceNameSnake}}.go"
outpkg: mocks
packages:
  "flamingo.me/httpcache":
    interfaces:
      Backend:
      TagSupporting: