name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.15', '1.*' ]
    name: With Go ${{ matrix.go }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Get dependencies
        run: go get -v -t -d ./...
      - name: Test
        run: go test -race -tags=integration ./...
  static-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.*' ]
    name: Static checks
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Get dependencies
        run: go get -v -t -d ./...
      - name: Go Vet
        run: go vet ./...
      - name: Go Fmt
        run: |
          fmt=$(gofmt -l .)
          test -z $fmt || (echo "please run gofmt" ; echo $fmt ; exit 1)
      - name: Go Lint
        run: go run golang.org/x/lint/golint@v0.0.0-20210508222113-6edffad5e616 -set_exit_status $(go list ./...)
      - name: Go Cyclo
        run: go run github.com/fzipp/gocyclo/cmd/gocyclo@v0.6.0 -over 20 .
      - name: Spelling
        run: go run github.com/client9/misspell/cmd/misspell@v0.3.4 -error .
      - name: In effective assignments
        run: go run github.com/gordonklaus/ineffassign@v0.0.0-20220928193011-d2c82e48359b  .
      - name: Go Generate
        run: |
          go generate ./...
          git diff --quiet  || (echo 'generated go files are not up to date, check go generate, go.sum and go.mod' ; git diff ; exit 1)